// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: crocospans.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SizeBytes int64      `protobuf:"varint,2,opt,name=SizeBytes,proto3" json:"SizeBytes,omitempty"`
	Count     int64      `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	Requests  []*Request `protobuf:"bytes,4,rep,name=Requests,proto3" json:"Requests,omitempty"`
}

func (x *RequestBatch) Reset() {
	*x = RequestBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crocospans_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBatch) ProtoMessage() {}

func (x *RequestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_crocospans_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBatch.ProtoReflect.Descriptor instead.
func (*RequestBatch) Descriptor() ([]byte, []int) {
	return file_crocospans_proto_rawDescGZIP(), []int{0}
}

func (x *RequestBatch) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RequestBatch) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RequestBatch) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTimeUnixNano uint64 `protobuf:"fixed64,1,opt,name=StartTimeUnixNano,proto3" json:"StartTimeUnixNano,omitempty"`
	EndTimeUnixNano   uint64 `protobuf:"fixed64,2,opt,name=EndTimeUnixNano,proto3" json:"EndTimeUnixNano,omitempty"`
	TraceID           string `protobuf:"bytes,3,opt,name=TraceID,proto3" json:"TraceID,omitempty"`
	TestRunID         int64  `protobuf:"varint,4,opt,name=TestRunID,proto3" json:"TestRunID,omitempty"`
	Scenario          string `protobuf:"bytes,5,opt,name=Scenario,proto3" json:"Scenario,omitempty"`
	Group             string `protobuf:"bytes,6,opt,name=Group,proto3" json:"Group,omitempty"`
	HTTPUrl           string `protobuf:"bytes,7,opt,name=HTTPUrl,proto3" json:"HTTPUrl,omitempty"`
	HTTPMethod        string `protobuf:"bytes,8,opt,name=HTTPMethod,proto3" json:"HTTPMethod,omitempty"`
	HTTPStatus        int64  `protobuf:"varint,9,opt,name=HTTPStatus,proto3" json:"HTTPStatus,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crocospans_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_crocospans_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_crocospans_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetStartTimeUnixNano() uint64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *Request) GetEndTimeUnixNano() uint64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

func (x *Request) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

func (x *Request) GetTestRunID() int64 {
	if x != nil {
		return x.TestRunID
	}
	return 0
}

func (x *Request) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetHTTPUrl() string {
	if x != nil {
		return x.HTTPUrl
	}
	return ""
}

func (x *Request) GetHTTPMethod() string {
	if x != nil {
		return x.HTTPMethod
	}
	return ""
}

func (x *Request) GetHTTPStatus() int64 {
	if x != nil {
		return x.HTTPStatus
	}
	return 0
}

var File_crocospans_proto protoreflect.FileDescriptor

var file_crocospans_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x72, 0x6f, 0x63, 0x6f, 0x73, 0x70, 0x61, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x6f, 0x0a, 0x0c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69,
	0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53,
	0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b,
	0x0a, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0xa5, 0x02, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x06, 0x52, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x69,
	0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0f,
	0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x75, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x75, 0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x54, 0x54,
	0x50, 0x55, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x54, 0x54, 0x50,
	0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x54, 0x54, 0x50, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x48, 0x54, 0x54, 0x50, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x54, 0x54, 0x50, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x48, 0x54, 0x54, 0x50, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_crocospans_proto_rawDescOnce sync.Once
	file_crocospans_proto_rawDescData = file_crocospans_proto_rawDesc
)

func file_crocospans_proto_rawDescGZIP() []byte {
	file_crocospans_proto_rawDescOnce.Do(func() {
		file_crocospans_proto_rawDescData = protoimpl.X.CompressGZIP(file_crocospans_proto_rawDescData)
	})
	return file_crocospans_proto_rawDescData
}

var file_crocospans_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_crocospans_proto_goTypes = []interface{}{
	(*RequestBatch)(nil), // 0: client.RequestBatch
	(*Request)(nil),      // 1: client.Request
}
var file_crocospans_proto_depIdxs = []int32{
	1, // 0: client.RequestBatch.Requests:type_name -> client.Request
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_crocospans_proto_init() }
func file_crocospans_proto_init() {
	if File_crocospans_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_crocospans_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crocospans_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crocospans_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crocospans_proto_goTypes,
		DependencyIndexes: file_crocospans_proto_depIdxs,
		MessageInfos:      file_crocospans_proto_msgTypes,
	}.Build()
	File_crocospans_proto = out.File
	file_crocospans_proto_rawDesc = nil
	file_crocospans_proto_goTypes = nil
	file_crocospans_proto_depIdxs = nil
}
